# Generated by Django 3.2.4 on 2021-06-17 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='monitorDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domainName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('interval', models.IntegerField(default=0)),
                ('startDate', models.DateTimeField(blank=True, null=True)),
                ('endDate', models.DateTimeField(blank=True, null=True)),
                ('upTime', models.IntegerField(default=0)),
                ('downTime', models.IntegerField(default=0)),
                ('isNotification', models.BooleanField(default=True)),
                ('notificationInterval', models.IntegerField(default=60)),
                ('lastNotificationTime', models.DateTimeField(blank=True, null=True)),
                ('SSLEnable', models.BooleanField(default=False)),
                ('SSLInterval', models.IntegerField(default=0)),
                ('isperfomance', models.BooleanField(default=False)),
                ('perfomanceinterval', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='sslCountDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isSSL', models.BooleanField(default=True)),
                ('SSLCheckTime', models.DateTimeField(blank=True, null=True)),
                ('SSLDetails', models.TextField()),
                ('monitorDetailsId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitemonitor.monitordetails')),
            ],
        ),
        migrations.CreateModel(
            name='performanceCountDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_performance', models.BooleanField(default=True)),
                ('performance_checktime', models.DateTimeField(blank=True, null=True)),
                ('performance_data', models.TextField()),
                ('monitor_details_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitemonitor.monitordetails')),
            ],
        ),
        migrations.CreateModel(
            name='monitorCountDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField(blank=True, null=True)),
                ('endTime', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('up', 'UP'), ('down', 'DOWN')], max_length=20)),
                ('monitorDetailsId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitemonitor.monitordetails')),
            ],
        ),
    ]
